### ISSUE TITLE
Contact form on website not working

### ISSUE THREAD

**Issue by Fougere87** [theislab/archmap#84]
Hi 
I tried to use the contact form of the website (www.archmap.bio) several times to ask for adding other reference data, but it throws an error at each attempt. 
Are others facing the same issue ? 

Best, 
Chloé

**Comment by chelseabright96** [comment]
Hi Chloé!
Thanks for reaching out! Apologies that the contact form was not working for you. This has been fixed and is working now if you'd like to submit again. You can also get in contact through archmap.bio@gmail.com :) 
Best,
Chelsea
